### ISSUE TITLE
Little question about the program

### ISSUE THREAD

**Issue by ccmywish** [flrnd/ching_cli#2]
Thank you very much for making this program!!!!!!

I came across the `ching` program from an old UNIX manual, I really want to try it. But I only found it on NetBSD source tree, I wanted to compile it, but failed, because I am very unfamiliar with BSD.

I'm curious how you know about the original source program, did you compile the C source? Does it output the same just look like your go program do?

**Comment by flrnd** [comment]
Hey thank you.

Yes, I compiled it on a netbsd virtual machine. Mine is simpler, the original Unix ching output hexagram and lines definitions (with it's own translation I guess). I didn't want to 'steal' its data file so I output only the results instead.

**Comment by ccmywish** [comment]
Thanks for your reply.  I'll try it on NetBSD sometime. 

Have a nice day ~
